# Generated by Django 6.0 on 2025-12-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('job_role', models.CharField(choices=[('Barista', 'Barista'), ('Junior Barista', 'Junior Barista'), ('Trainer', 'Trainer')], max_length=100)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('negotiable', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
