# Generated by Django 6.0 on 2025-12-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Post', '0002_remove_job_job_role_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
