# Generated by Django 6.0 on 2026-03-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Post', '0005_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
