# Generated by Django 6.0 on 2026-03-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Post', '0011_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
