# Generated by Django 6.0 on 2026-03-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Post', '0012_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Pokhara', max_length=255),
            preserve_default=False,
        ),
    ]
