# Generated by Django 6.0 on 2026-04-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Post', '0015_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti')], default='esewa', max_length=20),
        ),
    ]
