# Generated by Django 6.0 on 2026-03-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('APPLICANT', 'Applicant'), ('RECRUITER', 'Recruiter')], max_length=20),
        ),
    ]
